name: Check posts

on:
  repository_dispatch:
   types: [trigger-check-posts]

jobs:
  check-posts:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run check-posts
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          PUBLISH_API_ROUTE: ${{secrets.PUBLISH_API_ROUTE}}
          APP_ACCESS_TOKEN: ${{secrets.APP_ACCESS_TOKEN}}
          REQUEST_USER_AGENT: ${{secrets.REQUEST_USER_AGENT}}
        run: npx ts-node src/check-post.ts
